### ISSUE TITLE
In lines L921-925 error logic for size

### ISSUE THREAD

**Issue by perestoronin** [RadeonOpenCompute/ROCK-Kernel-Driver#118]
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/5b46cf51a9b3166f6da30e2d4508d3ff48bce5de/drivers/gpu/drm/amd/pm/amdgpu_pm.c#L921-L925

Need replace `size +=` on `size =` ?

**Comment by kentrussell** [comment]
Size is cumulative. Overwriting it each time won't help. Basically we're passing in the buf+size to get the next clock and increasing the size of the clocks. Then we add the next clock, and the next clock. Making it = instead of += will essentially just give us OD_CCLK and will drop the previous clock levels. If we were doing a case based on the OD_* fields, then it should be size=, but since we're putting all of it together in the same buf, it should be +=
