### ISSUE TITLE
1.3 opencl support

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCK-Kernel-Driver#15]
Hey, 

I read that 1.3 kernel/boltzman/hcc/etc should support OpenCL, is this true?

**Comment by gstoner** [comment]
No,  we said on Dec 14th we will be releasing a OpenCL  for ROCm

Greg
On Dec 1, 2016, at 3:16 PM, ♦♣♠♥ <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey,

I read that 1.3 kernel/boltzman/hcc/etc should support OpenCL, is this true?

**Comment by Dekken** [comment]
OK thanks

**Comment by Dekken** [comment]
Could you tell me how it will installed, i.e. I doubt it will be through the APP SDK

**Comment by jedwards-AMD** [comment]
No, it will be a debian or rpm package, just like the other ROCm packages. The install location will be /opt/rocm, like the other components.

**Comment by Dekken** [comment]
Excellent thanks

**Comment by Dekken** [comment]
Any chance you can let me know A) When it will be released and B) What the package name is?

Also C) Is it possible to build it myself?

**Comment by jedwards-AMD** [comment]
It is not open source, so you will not be able to build it. It will be distributed as an installable binary for both apt and dnf installations in two packages, opencl-rocm and opencl-rocm-dev. I cannot tell you the release date, but it should be soon.

**Comment by Dekken** [comment]
Cheers I'll keep an eye on the repo

**Comment by ekondis** [comment]
Not open source? I thought this was going to be released under the gpuopen philosophy like the rest software stack.

**Comment by johnbridgman** [comment]
The initial preview is a step along the way. We are still going through the code and replacing bits we can't open source with code that we can.

**Comment by jedwards-AMD** [comment]
John is correct. This version is the Beta version of OpenCL, and is binary only. The final official release will be open source.

**Comment by gstoner** [comment]
We will be bring OpenCL with full open source in the new year we had little more work to sanitize the code  and few more modules we want to replace prior to this happing.  One more big step is submitting the conformance log to Khronos Group when we hit GA  to have Compliant OpenCL 1.2 compliant product.  Instead waiting for all of this to happen.  To meet our commitment to number of our customer who use Ubuntu and Fedora we are releasing the developer preview as promised so they can begin helping us test OpenCL prior our GA.  One thing we still lot more performance turning to do so this right now is more for testing functionality.

I want rest asursed we will be releasing the full OpenCL stack as Open Source,  we have already started with Compiler front-end in CLANG and LLVM  AMDGPU native code generator.  What is left is Language Runtime and it mapping to ROCr and it other subsystems. I am working with the team to make this happen as soon as possible.

One thing the team has worked hard over the last year.  Since April we launch ROCm 1.0 had  5 releases of ROCm with now the release of ROCm 1.4   We also want to thank you for your patience as we bring OpenCL to ROCm.  We close to complete language foundation for ROCm with  HCC, HIP, OpenCL, and Python.    We are now focused on bring more libraries and Application to the platform in the new year.

We also want to wish you a Happy Holidays and Fantastic New Year

Greg

On Dec 16, 2016, at 11:07 AM, James Edwards <notifications@github.com<mailto:notifications@github.com>> wrote:


John is correct. This version is the Beta version of OpenCL, and is binary only. The final official release will be open source.

**Comment by Dekken** [comment]
Very glad to hear that Greg, congratulations all round. Is there a sign up for the dev preview? I'm happy to put some time in to show support for general Debian.

**Comment by gstoner** [comment]
Let me check with DevOps it should be in 1.4 package.  I not seeing it on release notes.

https://github.com/RadeonOpenCompute/ROCm    You see 1.4 is posted.

Greg

On Dec 16, 2016, at 3:30 PM, ♦♣♠♥ <notifications@github.com<mailto:notifications@github.com>> wrote:


Very glad to hear that Greg, congratulations all round. Is there a sign up for the dev preview? I'm happy to put some time in to show support for general Debian.

**Comment by Dekken** [comment]
So it is! Kernel upgrade doesn't seem to be yet in the repo but I'll give it a go

**Comment by gstoner** [comment]
the package may still be filtering up.

greg
On Dec 16, 2016, at 4:11 PM, ♦♣♠♥ <notifications@github.com<mailto:notifications@github.com>> wrote:


So it is! Kernel upgrade doesn't seem to be yet in the repo but I'll give it a go

**Comment by ekondis** [comment]
That's great! ROCm seems to significantly improve release after release. I've noticed significant speed-ups from 1.2 to 1.3 release and the OpenCL support was a significant missing part.

Keep on the good work and I wish you a happy new year.

**Comment by gstoner** [comment]
Thank you,    With the CLANG 4.0 compiler update to HCC you see more improvements,  Efficient Register Utilization is big area of focus.  We have lot more to come.

greg
On Dec 17, 2016, at 4:00 AM, Elias <notifications@github.com<mailto:notifications@github.com>> wrote:


That's great! ROCm seems to significantly improve release after release. I've noticed significant speed-ups from 1.2 to 1.3 release and the OpenCL support was a significant missing part.

Keep on the good work and I wish you a happy new year.
