### ISSUE TITLE
I would like to know, is there a way to disable the L2 cache for certain variables in sea islands ISA. I may access few variables which might be accessed by another controller residing on GPU DDR. I dont want to have cache coherency problem. Is there a instruction like volatile working on the global DDR memory which will bypass L2 cache during read / write back

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/ROCK-Kernel-Driver#16]
Is there a instruction in ISA for sea island architecture to invalidate and flush the cache L2 in specific.

**Comment by jvesely** [comment]
memory instructions (FLAT,MUBUF,MTBUF,MIMG) include system level coherence (SLC) and global level coherence (GLC) flags which are used to control cache policies.

**Comment by jlgreathouse** [comment]
Our discrete GPUs do not offer any shader instructions that allows for flush/invalidation of the L2 cache. We have instructions for flushing the L1 data caches to the L2 coherence point, but L2 flushes are only possible from the command processor at this time -- and the command processor will primarily do these at the end of a kernel. It's slightly more complex than that internally, but suffice it to say that you will be unable to forcibly push dirty data out of the L2 cache in the manner you desire or forcibly remove a line from the cache so that you see updated values from the memory controller.

In addition, the bits that @jvesely mention are also not likely to do exactly what you want. He is correct that SLC and GLC control cache policies. By setting the GLC and SLC bits, you can cause loads, stores, and atomics to act slightly differently in the memory system.

Loads have the following semantics:
- GLC = 0 / SLC = 0: Normal loads. LRU replacement in the L1 cache. LRU replacement in the L2 cache.
- GLC = 0 / SLC = 1: Streaming. LRU replacement in the L1 cache. "Streaming" replacement in the L2 cache (LRU chain not updated).
- GLC = 1 / SLC = 0: Bypass L1, data stored in L1 with LRU replacement. LRU replacement in the L2 cache.
- GLC = 1 / SLC = 1: Bypass L1, don't store data in L1. "Streaming" replacement in the L2 cache (LRU chain not updated).

Stores have the following semantics:
- GLC = 0 / SLC = 0: Normal stores. L1 is write-through, buffered w/ write-combining, only whole-line writes remain in cache. LRU replacement in the L2 cache.
- GLC = 0 / SLC = 1: Normal stores. L1 is write-through, buffered w/ write-combining, only whole-line writes remain in cache. "Streaming" replacement in the L2 cache (LRU chain not updated)
- GLC = 1 / SLC = 0: Normal stores. L1 is write-through, buffered w/ write-combining, only whole-line writes remain in cache. LRU replacement in the L2 cache.
- GLC = 1 / SLC = 1: L1 is write-through, buffered w/ write-combining, data not left in the L1. "Streaming" replacement in the L2 cache (LRU chain not updated)

Atomics have the following semantics:
- GLC = 0 / SLC = 0: Returns pre-atomic value from memory. L1 is bypassed and not allocated. LRU replacement in the L2 cache.
- GLC = 0 / SLC = 1: Returns pre-atomic value from memory. L1 is bypassed and not allocated. "Streaming" replacement in the L2 cache (LRU chain not updated)
- GLC = 1 / SLC = 0: Returns post-atomic value from memory. L1 is bypassed and not allocated. LRU replacement in the L2 cache.
- GLC = 1 / SLC = 1: Returns post-atomic value from memory. L1 is bypassed and not allocated. "Streaming" replacement in the L2 cache (LRU chain not updated)

You can use these caching policies to properly [handle coherence and memory models within a GPU](https://llvm.org/docs/AMDGPUUsage.html#memory-model), but note that none of these policies will allow you to push data out of or evict data from the L2 cache. As such, they would not, by themselves, allow you to maintain coherence with some entity outside the GPU.

There are a few steps you could take for what you want, however:

1. The "big hammer" approach: you can entirely disable the L2 cache of your GPUs in ROCm. To do this, set the environment variable `HSA_DISABLE_CACHE=1`. This will cause ROCt to set all memory regions for your program as uncacheable.
2. You could modify the memory allocator in ROCt (the thunk) to [set the flag](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/roc-1.8.x/src/fmm.c#L1034) `KFD_IOC_CACHE_POLICY_COHERENT` for memory regions you are interested in when it is requesting that region from the KFD. This will set the MTYPE for that region to in the GPU to UC, or uncacheable. Technically, when you set HSA_DISABLE_CACHE, it sets UC for *all* regions. However, with enough work in the thunk, you could mark particular allocations that you are interested in so that they are marked UC and thus bypass the L2 cache.

For the latter case, you could look into how `hipHostMallocCoherent` is implemented. This is used for some of our multi-GPU libraries so that they can synchronize with one another. The variables will live on the host and be communicated to the host over PCIe in current hardware implementation, but they will also be marked as non-cached (I believe they are allocated from [this region set aside by the Thunk](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/roc-1.8.x/src/fmm.c#L1617)).

[This recent mailing list conversation ](https://reviews.llvm.org/D39350)may prove useful to you, @VishwasRao17.
