### ISSUE TITLE
When to expect DKMS support

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/ROCK-Kernel-Driver#17]
What is the status of DKMS support for allowing to use ROCm with pre-compiled kernels? A related question is when (if ever) will ROCm be in mainline?

An additional request is to make the ROCm module compatible with GrSecurity patches.

**Comment by trentdhooge** [comment]
With the release of ROCm 1.6.x , is there now DKMS support? It looks to still be a stand alone kernel. Any update on DKMS, or am I just not seeing it, and it's done. Thanks.

**Comment by fxkamd** [comment]
No DKMS support in 1.6.1. We were planning for it in 1.6 which is why we used a kernel based on our hybrid branch. But the schedule didn't like up for testing and supporting multiple OSes with DKMS kernels. We are still working on bringing DKMS support in a future release, but probably not the 1.6.x series.

**Comment by bradmccormack** [comment]
Hello, any updates on this please?

**Comment by gstoner** [comment]
With the upcoming 1.7 release, we are moving to DKMS Based Kernel Driver Install 

We will be supporting 
- Ubuntu 16.04 
- Redhat Enterprise Linux  7.3 
- CENTOS 7.3 
- SUSE 12 SP2

**Comment by madscientist159** [comment]
@gstoner If you don't mind my asking, when is 1.7 due out?  I'm quite eager to move off of W10 and onto something more suited for heavy-duty work.

I ask partly because there doesn't seem to be any public commits lately in the kernel tree here on GitHub.  Is development occuring in a private branch?

**Comment by bradmccormack** [comment]
@gstoner thanks for the answer. @madscientist159 Same question here.

**Comment by madscientist159** [comment]
@gstoner So, I'm guessing we should check back in 2018?  Is Navi a target for ROCm down the line?

**Comment by anoother** [comment]
It's working on Linux now. With the Ubuntu repo enabled:

```sudo apt update
sudo apt remove rocm
sudo apt install rocm-*```

Even builds successfully against my snapshot of the `agd5f/drm-next-4.16-wip` kernel. so we can finally have the latest amdgpu/DC *and* rocm together. Not actually tested compute yet, though.

**Comment by gstoner** [comment]
Yes we rolled DKMS support out this week finally,  next up is RHEL/Centos Support then SUSE with DKMS.
