### ISSUE TITLE
remind user to boot to the kfd kernel

### ISSUE THREAD

**Issue by yxsamliu** [RadeonOpenCompute/ROCK-Kernel-Driver#3]
If grub2 loader is used, Ubuntu boots to the default old kernel after installing the kfd kernel driver, ROCR runtime won't work and the sample will crashes. To load the kfd kernel, users need to choose the "Advanced Options for Ubuntu" in grub menu then choose the kfd kernel.

Maybe README.md should add a note about that, otherwise it causes surprise for inexperienced users.

**Comment by mattmacy** [comment]
Agreed. I quickly figured this out myself, but the fact that I hit it at all indicates that the documentation should be updated. I initially assumed that installing the ROCK kernel would not only update grub, but make the ROCK kernel the default.

**Comment by fxkamd** [comment]
I think the reason is that out ROCK kernel version is older than your stock kernel. The Ubuntu generated grub config will pick the highest kernel version as the default kernel. I guess the documentation should include instructions to set GRUB_DEFAULT in /etc/default/grub. The trouble is that you need to match the menu entry ID exactly.

**Comment by arodrigx7** [comment]
I'll update the README.md to add a note about this. This isn't really a grub2 specific issue, but instead it depends on whether your current kernel alphabetically sorts "lower" than the roc kernel. This is true for newer ubuntu releases.

**Comment by arodrigx7** [comment]
Instructions on how to change the default have been added to README.md so I'm closing this issue.
