### ISSUE TITLE
GPU fan noise after ROCK install

### ISSUE THREAD

**Issue by bragadeesh** [RadeonOpenCompute/ROCK-Kernel-Driver#4]
Hello,

I have an Intel Haswell + R9 Nano machine with Ubuntu 14.04. After a clean install of the OS, I followed the instructions to install ROCK. After rebooting with kfd kernel, my GPU fan is always in high speed and the fan noise is annoying.

The same machine is setup for dual boot with Windows. On windows side, the problem does NOT happen with Catalyst drivers.

Also in the past, I have used the same machine with Ubuntu Linux and earlier version of Boltzmann stack (from January) without issues.

I would like a solution to this fan problem. Is this known issue? Is there a fix?

**Comment by arodrigx7** [comment]
Hi bragadeesh,

I've added a note to the README regarding this known issue. On consumer grade hardware thermal control was not working correctly and was causing the cards to overheat. As a temporary workaround fans are set to 100% for Nano, Fury and Fury X products.

**Comment by mattmacy** [comment]
Gulp, any idea when that will be fixed?

**Comment by arodrigx7** [comment]
It will be fixed in 1.1, which should be in the coming weeks.

**Comment by mattmacy** [comment]
I'm in the process of updating FreeBSD's DRM to 4.6 to bring i915 up to Kaby Lake and bring in amdgpu support so I can use my R9 cards. I'm a little concerned that ROCK is being developed against 4.1. What are your plans for updating to 4.6 or at least something more recent? I see kfd in the 4.6-rc4 tree, but don't know how it reflects your progress.

Thanks.

**Comment by jedwards-AMD** [comment]
We are planning on updating to (at least) 4.4 by the 1.1 release.

**Comment by mattmacy** [comment]
4.6 is on rc4 so, presumably, will be released shortly. What is your reasoning behind 4.4?

**Comment by johnbridgman** [comment]
4.4 was the most recent released kernel when we started the work. The 4.6 kernel won't be out for another month or so, so we're planning to use 4.4 for our upcoming release. 

In parallel with the next official release we will be rebasing on evolving 4.6 as part of getting ready for upstreaming (targeting 4.7).  

Great news about updating FreeBSD's DRM, that's going to make a lot of people happy.

**Comment by mattmacy** [comment]
> 4.4 was the most recent released kernel when we started the work. The 4.6 kernel won't be out for another month or so, so we're planning to use 4.4 for our upcoming release.

That makes sense.

> In parallel with the next official release we will be rebasing on evolving 4.6 as part of getting ready for upstreaming (targeting 4.7).

That might work out perfectly. I'm hoping to have amdgpu working mid to late May. Does that line up with your rough guesstimate of when you'll be rebasing against 4.6/4.7?

> Great news about updating FreeBSD's DRM, that's going to make a lot of people happy.

Yes. It will be nice to support late model hardware again for a change. With luck, keeping the DRM and drivers much closer to upstream (by using linuxkpi shims wherever possible) it will be easier to keep up to date. Only time will tell.

Thanks for ROCK/ROCR.

**Comment by johnbridgman** [comment]
> That might work out perfectly. I'm hoping to have amdgpu working mid to late May. Does that line up with your rough guesstimate of when you'll be rebasing against 4.6/4.7?
Sounds right. I hope to be running well ahead of you but things don't always go as planned :)

**Comment by gstoner** [comment]
ROCm  Platform  (  ROCK+ROCR + HCC + HIP) Ben Sander and i have been driving to  happen,   I am really excited to finally be delivering first class GPU computing solution to open source market.   AMDGPU Native ISA compiler is also going to improve quickly.  We delivering a lot great to capabilities in it as well i would track.

 I would love to see the full ROCm platform  running in  FreeBSD,  I still love BSD, little know fact even NCD X-terminals used a stripped down BSD kernel and I spent my college day developing code on SunOS 4.x.  I have soft spot for BSD.

We still have lot more coming..   Also a cool thing  Continuum Analytics  Anaconda with Numba  now runs with ROCm via ROCR and it is fully open source..

On Apr 19, 2016, at 4:40 PM, Matthew Macy <notifications@github.com<mailto:notifications@github.com>> wrote:


4.4 was the most recent released kernel when we started the work. The 4.6 kernel won't be out for another month or so, so we're planning to use 4.4 for our upcoming release.

That makes sense.

In parallel with the next official release we will be rebasing on evolving 4.6 as part of getting ready for upstreaming (targeting 4.7).

That might work out perfectly. I'm hoping to have amdgpu working mid to late May. Does that line up with your rough guesstimate of when you'll be rebasing against 4.6/4.7?

Great news about updating FreeBSD's DRM, that's going to make a lot of people happy.

Yes. It will be nice to support late model hardware again for a change. With luck, keeping the DRM and drivers much closer to upstream (by using linuxkpi shims wherever possible) it will be easier to keep up to date. Only time will tell.

Thanks for ROCK/ROCR.

**Comment by fxkamd** [comment]
Just wanted to mention that our ioctl ABI is not final yet. In fact, it's currently incompatible with upstream. We have to clean that up in the next few weeks.

**Comment by mattmacy** [comment]
Greetings fellow ROCm travellers,
I have a quick update and a few furrther questions. I have now have an essentially unmodified 4.6-rc5 DRM and i915 driver working. The unmodified is to emphasize that all the porting work is outside the driver in the linuxkpi compatibility layer. Consequently, bringing up amdgpu should be fairly trivial once I get my Thinkpad e565 this weekend. At the moment I can only say that amdgpu and amdkfd build. Most users seem to care only about i915 support. However, for me it's just a stepping stone to FreeBSD support for ROCm so I can run machine learning codes (I'll have to port the CUDA to HCC).

Now a few questions:
1) How important is userptr support? FreeBSD doesn't currently have the necessary VM callbacks. They would not be difficult to add, but a) I need to motivate making changes to the core kernel b) I'm not sure how to test userptr support.

2) What, if anything, uses prime support other than integrated to discrete GPU switching on laptops? I'm wondering how to test the new (to FreeBSD) prime support without a laptop with a discrete GPU.

3) Where are you with respect to your roadmap? How long do you think until you converge with whatever the latest release of Linux? Since I mainly care about ROCm should I be using your branch rather than 4.6? Or ideally will the two converge in the coming weeks?

4) libsp3 is still closed source and linux only. This could end up being a bit of a showstopper for the '0' in ROCm. Any updates on either open sourcing it or allowing us to redistribute a binary compiled under NDA?

Thanks in advance.

**Comment by fxkamd** [comment]
To answer question 2: Prime is a general mechanism for sharing memory between different devices and drivers by using driver-agnostic buffer handles for sharing. In ROCm we're using it for sharing memory between graphics and compute APIs. BOs can be exported by the graphics driver using Prime APIs and imported by ROCm so that memory can be shared between graphics and compute APIs. This is still in development and not supported in any official way at the application programming level at this point.

**Comment by mattmacy** [comment]
@fxkamd Can you suggest any straightforward way of testing prime support outside of ROCm? The dmabuf implementation is all new code and there may be other gaps in the linuxkpi. So debugging any issues in the context of your compute APIs sounds potentially painful.
Thanks.

**Comment by jedwards-AMD** [comment]
To answer question 4: We are still in the process of working out the libsp3 details.

**Comment by fxkamd** [comment]
The prime support in amdgpu isn't really ROCm-specific. The ability to export and import DMABuf handles to/from GEM objects is nothing new. For example the front buffer of an application would be shared with a composite manager using the Prime APIs. I'm not familiar with the Mesa, Xorg, compiz, gbm, mir, wayland, etc. implementations, so I can't point you at where exactly that's implemented. Also, depending on the DRI protocol version I think it may use the GEM flink buffer sharing API rather than prime.

One should be able to write a unit test app that exports a GEM buffer from a GPU in process A and import it on a different GPU or in a different process B, using just libdrm_amdgpu APIs.

What we added is the ability to import Prime buffer handles into the HSA SVM address space.

**Comment by mattmacy** [comment]
I'm not at all acquainted with the user space side of things myself. That's why I was asking for suggestions.
Thanks.

**Comment by mattmacy** [comment]
@gstoner are there no public resources such as mailing lists or irc channels for amdgpu?

**Comment by arodrigx7** [comment]
Hey @mattmacy 

For amdgpu related discussions you can use the dri-devel mailing list and irc channels. These resources are used for discussion of all DRM based gpu drivers:
https://lists.freedesktop.org/mailman/listinfo/dri-devel

**Comment by gstoner** [comment]
Solved in ROCm 1.1.1
