### ISSUE TITLE
OpenCL installation issue on VM

### ISSUE THREAD

**Issue by olivier-dj** [RadeonOpenCompute/ROCK-Kernel-Driver#41]
Hello I'm quite new in the field, I want to install drivers for an Amethyst XT [Radeon R9 M295X Mac Edition / R9 380X] GC with pci passthrough on a ubuntu 16.04 VM launched from an Openstack host which runs ubuntu 16.04. The final goal is to be able to use OpenCL on the VMs (for Caffe or Veles Deep Learning). After the system changes for passthrough, GC is visible on the guest OS (before any driver installation):

```
$ lshw
   *-display:1 UNCLAIMED
         description: VGA compatible controller
         product: Amethyst XT [Radeon R9 M295X Mac Edition / R9 380X]
         vendor: Advanced Micro Devices, Inc. [AMD/ATI]
         physical id: 5
         bus info: pci@0000:00:05.0
         version: f1
         width: 64 bits
         clock: 33MHz
         capabilities: pm pciexpress msi vga_controller cap_list
         configuration: latency=0
         resources: memory:e0000000-efffffff memory:f2000000-f21fffff ioport:c000(size=256) memory:feb80000-febbffff memory:febc0000-febdffff
```

Then I tried several options for the driver.
With ROCm, I finally had the same issues as mentioned in [issue 307](https://github.com/RadeonOpenCompute/ROCm/issues/307) using rocm-smi, clinfo, helloworld.

With amdgpu-pro,  clinfo didn't even produce an output, hanged and even survive the kill -s SIGKILL. Here is the result of dmesg after installing the driver and rebooting 
[dmesg.txt](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/files/1664379/dmesg.txt)

So my questions are:
- Having the KVM hypervisor, is there a solution a bit more production-ready for an Openstack deployment than editing manually the pci config after the launch of the guest OS with ROCm as explained in the issue 307.
- Is there maybe something I did wrong in my attempts to get this dmesg output and/or is the problem I had with amdgpu-pro related to the one i encountered with ROCm.

**Comment by gstoner** [comment]
You failing due to  not allowing PCIe Atomics aka atomic completor through


ROCm Virtualization & Containers
KVM Passthrough
Setup host passthrough mode
Assume we use an intel system that supports VT-d , with fresh ubuntu 16.04 installed

a. Install necessary packages and prepare for pass through device

sudo apt-get install qemu-kvm qemu-system bridge-utils virt-manager ubuntu-vm-builder libvirt-dev
add following modules into /etc/modules
vfio
vfio_iommu_type1
vfio_pci
kvm
kvm_intel
add intel_iommu=on in /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT=”quiet splash intel_iommu=on”
sudo update-grub

Blacklist amdgpu by adding the following line to /etc/modprobe.d/blacklist.conf
blacklist amdgpu

b. Bind pass through device to vfio-pci

Create a script file (vfio-bind) under /usr/bin. The script file has the following content:
#!/bin/bash
modprobe vfio-pci
for dev in "$@"; do
        vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
        device=$(cat /sys/bus/pci/devices/$dev/device)
        if [ -e /sys/bus/pci/devices/$dev/driver ]; then
                echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
        fi
        echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id
done

Make it executable by enter the command
chmod 755 vfio-bind

Bind the device to vfio by running the command for the three pass through devices

lspci -n -d 1002:
        83:00.0 0300: 1002:7300 (rev ca)

vfio.bind 0000:83:00.0

sudo reboot

c. Pass through device to guest VM

Start VMM by running “virt-manager” as root. Follow the on screen instruction to create one virtual machine(VM), make sure CPU copy host CPU configuration, network use bridge mode.

Add Hardware –> Select PCI Host device, select the appropriate device to pass through. ex:0000:83:00.0

sudo setpci -s 83:00.0 CAP_EXP+28.l=40
sudo reboot

After reboot, start virt-manager and then start the VM, inside the VM , lspci -d 1002: should shows the pass through the device.

**Comment by gstoner** [comment]
Note this forum is for the ROCm driver not AMDGPUpro

**Comment by olivier-dj** [comment]
Hello, thank you for the quick answer,
What I meant by "After the system changes for passthrough" is exactly what you wrote above. The only difference is that I have an AMD processor and launch my VMs with Openstack. I already did all of these changes, BIOS svm and iommu activation, installed the packages, grub config, vfio ("Kernel driver in use: vfio-pci" with lspci -v) blacklisted amdgpu and so on, and I was already able to see the device on the VM with lspci (with lshw as well like mentioned in my first post). But I still got 
./HelloWorld
Failed to find any OpenCL platforms.
Failed to create OpenCL context.

The only differing point was that I didn't set the pci config with "sudo setpci -s 01:00.0 CAP_EXP+28.l=40".

So I created a new clean VM, I did this pci config command on the host OS, rebooted, started the VM and installed ROCm again, still have the same output with the hello world.
Moreover I still have the errors with amdgpu in [dmesg-2.txt](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/files/1667272/dmesg-2.txt), starting with :
`[   11.149941] BUG: unable to handle kernel paging request at ffffc91c00bfdfec
[   11.152008] IP: [<ffffffffc058d4bd>] smu7_populate_single_firmware_entry.isra.3+0x8d/0xf0 [amdgpu]`
that  I don't have before ROCm installation..

**Comment by olivier-dj** [comment]
I don't use display, and access both guest VM and host OS via ssh,  Openstack is configured as well to manage pci passthrough, and I've be able to see my Radeon R9 M295X Mac Edition / R9 380X with lspci from the VM since my first VM launch.. with lshw the card is first UNCLAIMED (no driver) and then after ROCm installation the this UNCLAIMED state disappears, which I find logical, but somehow how you can see in the dmesg something goes wrong..

**Comment by olivier-dj** [comment]
@gstoner I found the problem. I disabled the framebuffer in grub and now rocm-smi provides an output, got rid of the dmesg panic. Surprisingly I never saw any warnings about the fb for pci passthrough system config, noticed that checking /proc/iomem. Thank you for you help !

**Comment by gstoner** [comment]
Thank you.  I get this into Linux team 

G
