### ISSUE TITLE
one patch file for Ubuntu 18.04

### ISSUE THREAD

**Issue by wormwang** [RadeonOpenCompute/ROCK-Kernel-Driver#54]
Are u release one patch file for Ubuntu 18.04.
It will help merge with other version of kernel building.

**Comment by jlgreathouse** [comment]
Hi @wormwang 

At this time, no. We do not plan on releasing patch files to diff the ROCK driver repoistory vs. the upstream kernel or against any kernel in distros like Ubuntu. As it stands, this repository contains enough code to allow you to build a monolithic kernel, and the version it is based on will change with each ROCm release. If you would like, you could try diffing this repo against the Linux version shown in [the Makefile](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/master/Makefile).

If you instead install the `rock-dkms` package, your system will have the source code solely for the AMD drivers needed for ROCm. Because the DKMS module needs to be rebuilt for each kernel on your system, the package installs source code into `/usr/src/amdgpu-*`. These packages also contain the appropriate firmware for the drivers in this reposistory.

If you want to try to rebuild the DKMS module from the source contained in this repository, you might be interested in our [Experimental ROC](https://github.com/RadeonOpenCompute/Experimental_ROC) project.
