### ISSUE TITLE
expose HBM/memory temperature

### ISSUE THREAD

**Issue by akostadinov** [RadeonOpenCompute/ROCK-Kernel-Driver#69]
Hi presently one can see AMD Vega GPU temp
```
# cat /sys/class/hwmon/hwmon0/temp1_input 
56000
```

But there is no info about HBM temperature which is sometimes more important than GPU temperature. Sensor data is also undiscoverable:
```
# sensors
amdgpu-pci-0300
Adapter: PCI adapter
vddgfx:       +0.90 V  
fan1:        3012 RPM  (min =  400 RPM, max = 4900 RPM)
temp1:        +56.0°C  (crit = +89.0°C, hyst = -273.1°C)
power1:      129.00 W  (cap = 220.00 W)
...
```

HBM temperature information is available under windows so I assume it is a matter of the driver to expose it.

-- rocm-dkms-2.0.89-1.x86_64 vs AMD Vega frontier edition

**Comment by kentrussell** [comment]
The ROCK driver is based on amdgpu, so there would need to be support in the amdgpu kernel for that first. You can try e-mailing amd-gfx@lists.freedesktop.org to get a response from the amdgpu team. It's possible that the SMU doesn't support reporting these temperatures, which could be why they aren't reported, or it could just be that it needs to be implemented in the kernel, but e-mailing the amdgpu mailing list above is the best way to get that included. Once it's in the amdgpu kernel, we will bring it into ROCK. 

In general, we try not to put things in the ROCK that aren't in amdgpu. The exceptions are for things that **cannot** go into the Linux kernel, like the KCL (Kernel Compatibility Layer) which we use for DKMS, or P2P since that's still not upstreamable in its current state. For temperature monitoring of HBM and memory, that would definitely fall under the amdgpu umbrella.
