### ISSUE TITLE
5x Radeon Pro Duo (Polaris) BAR mem assign failure

### ISSUE THREAD

**Issue by sos-michael** [RadeonOpenCompute/ROCK-Kernel-Driver#78]
I've got a gigabyte mz31 + 7551p and 5x RPDs

I'm currently on F30, but I've tried all manor of distros and always end up with a bunch of:
amdgpu 0000:69:00.0: BAR 0: failed to assign [mem size 0x400000000 64bit pref]

Eventually it resolves:
amdgpu 0000:69:00.0: BAR 0: assigned [mem 0x2bfb0000000-0x2bfbfffffff 64bit pref]

but I'm stuck with 256MB GARTs:
amdgpu 0000:69:00.0: GART: 256M 0x000000FF00000000 - 0x000000FF0FFFFFFF

Which is less than ideal. I've done all the obvious stuff I can think of, and do I realize this could be a bios issue, but I figure it worth a try to ask for some advice. Rocminfo shows all 14 nodes and everything does work, just in this compromised state.

**Comment by fxkamd** [comment]
I think you're confusing two different things: BAR size and GART size. BAR is the window through which the CPU and peer GPUs can access framebuffer. GART size is the amount of system memory the GPU can map in kernel mode. GART size is deliberately small. We never need to map lots of memory in kernel mode at once.

The driver tries to resize the BAR, but that doesn't always work, especially on multi-GPU systems, due to lack of PCI resources. The GPU still works with the original small BAR (256MB) but with some performance penalty. In the context of ROCm it means we disable direct CPU and peer access to VRAM. Any memory copies between GPUs need to go through staging buffers in system memory.

**Comment by sos-michael** [comment]
You are correct! I totally have my terminology confused, forgive me for that. You've also correctly ascertained my end goal, I'm trying to avoid as many of those staging penalties as possible. I'm very new to ROCm, if there are known ways to work around this in the software I'm writing, but my goal is to be able address as much of the ~400GB of RAM available (system+gpu) available directly as possible. My workload scales exponentially in storage requirements.

**Comment by fxkamd** [comment]
I believe MI-series GPUs come with large-BAR Video-BIOSes that have a memory BAR the same size as the VRAM BAR from boot. So they don't depend on Linux resizing the BAR later. That avoids problems for example with brigdes not having enough address space available.

That said, large-BAR may still not solve your problem. It still depends on the System-BIOS assigning the BARs to physical addresses that can be addressed by peer-GPUs. Polaris is GFXv8, which can only support 40-bit physical addresses. You'll probably need a custom system BIOS that assigns 64-bit BARs to such low addresses. You may have better luck with GFXv9 (Vega) GPUs that can support 44-bit physical addresses. I believe the marketing name for Vega10 compute cards is MI-25. Vega20 would be MI-50 and MI-60.

**Comment by sos-michael** [comment]
My motherboard definitely supports large bar. its build for multigpu compute, but I'll get in touch with the manufacturer.

That said, do you think it could be related to this:
https://lists.freedesktop.org/archives/amd-gfx/2018-February/019123.html

Since the RPDs are behind a common PLX, they both would need to turned off for the set to be successful? I don't work much in c, but maybe I can make a change to driver? It seems like it would be straightforward enough? (famous last words?)

I've also got anther card on here (nvidia p4000) and it does not complain.

**Comment by fxkamd** [comment]
That sounds like a similar problem. Turning off all the cards would require that the driver instances for all cards coordinate. It would be a non-trivial change if it's possible at all. I think what you're suggesting would require something like this: The first GPU getting initialized would need to find all the other GPUs that are potentially behind the same bridge, ensure those GPUs aren't initialized already (because resizing their BAR after initialization would be bad), ensure they don't get initialized concurrently (some kind of locking or mutual exclusion) and then resize them all at once. It's not clear to me how the driver can be sure of the VRAM size of all the other GPUs without actually having run through at least part of the initialization sequence of those GPUs. So you may have to do some kind of partial initialization, and defer the resizing and complete initialization to some time after all GPUs have been discovered.

Like I said, not trivial.

**Comment by sos-michael** [comment]
I see what you are saying, but my problem is decidedly a more narrow case of it right? The person in the link has bifurcation where some of their single GPU cards are connected via the south bridge of their motherboard and some of them are directly connected to the CPU. Who knows what else is connected via that bridge, so turning it off is a no go. In contrast, all the Radeon Pro Duo have an on card PLX 8747 that is exists solely for the routing of those two GPUs upsteam. so my topology is:

7551p - 128 PCIe lanes
5 on card PLX 8747 collected via 8 lanes each to CPU
Each on card PLX is responsible for the 48 lane multiplexing of the two Polaris 12 GPUs on that card.

It follows that I would only have to turn on off that card's parent PLX? As you say, there are other consideration at play with timing, but these dual chip single card solutions should be a pre configured case, correct? Now that I think about it, shouldn't that case already be handled in driver for the Radeon Pro Duo or the Radeon Pro V340? If it fails because they are both set to 256MB at boot, but that value cannot change because they are behind a shared bridge which in turn needs to reprogrammed, how would it ever work correctly?

Sorry for the myriad of questions, I am trying to get my head around this and am likely missing something obvious.

**Comment by fxkamd** [comment]
The driver initialization doesn't have any special treatment for dual-GPU cards. To the driver the two GPUs look the same as two separate cards in separate PCIe slots. They are treated as completely independent devices (with maybe some exceptions for shared power and thermal management).

**Comment by sos-michael** [comment]
Gotcha. Thanks for your help all the same!
